# Generated by Django 4.1.2 on 2022-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshopapp', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
