# Generated by Django 4.1.2 on 2022-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftshopapp', '0004_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
